#Hugo configuration
title = "rsdfgert"
baseURL = "https:\/\/sdf.sdf.cas"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
